# research_task:
#   description: >
#     Conduct a thorough research about {topic}
#     Make sure you find any interesting and relevant information given
#     the current year is {current_year}.
#   expected_output: >
#     A list with 10 bullet points of the most relevant information about {topic}
#   agent: researcher

# reporting_task:
#   description: >
#     Review the context you got and expand each topic into a full section for a report.
#     Make sure the report is detailed and contains any and all relevant information.
#   expected_output: >
#     A fully fledged report with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: reporting_analyst

# analyze_spreadsheet_task:
#   description: >
#     Analyze the data from the provided Google spreadsheet and extract key insights.
#   expected_output: >
#     A summary of key insights and data points extracted from the spreadsheet.
#   agent: analyst

analyze_excel_task:
  description: >
    Analyze the data from the provided Excel file and extract key insights.
  expected_output: >
    A summary of key insights and data points extracted from the Excel file.
  agent: finance_analyst

financial_analysis_task:
  description: >
    Provide a comprehensive analysis of the company's financials based on the data provided by the finance analyst.
  expected_output: >
    A detailed financial report with strategic recommendations based on the company's financial data.
  agent: finance_manager
